# _config.yml — Jekyll + GitHub Pages

title: "News-letter"
description: "Điểm tin nhanh Ngành Nông Nghiệp – AgriS"
url: ""        # nếu dùng nnt471-collab.github.io/<repo>, để trống
baseurl: ""    # để trống khi deploy trên nhánh main

markdown: kramdown
highlighter: rouge

# KHÔNG dùng theme (dùng layout tùy biến)
# theme:

# Collections
collections:
  months:
    output: true
    permalink: /:collection/:name/
  # nếu sau này làm theo tuần, mở thêm:
  # weeks:
  #   output: true
  #   permalink: /:collection/:name/

# Mặc định cho months
defaults:
  - scope:
      path: ""
      type: "months"
    values:
      layout: month

include:
  - _includes
  - _layouts
  - assets

plugins: []
