title: "News-letter"
description: "Điểm tin nhanh Ngành Nông Nghiệp – AgriS"

# KHAI BÁO ĐÚNG CHO PROJECT PAGES:
url: "https://nnt471-collab.github.io"   # domain GitHub Pages của account
baseurl: "/News-letter"                   # tên repo (bắt đầu bằng dấu /)

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

collections:
  months:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope: { path: "", type: "months" }
    values: { layout: month, type: month }

include: [_includes, _layouts, assets]
plugins: []
