# _config.yml — cấu hình tối thiểu cho Jekyll + GitHub Pages

title: "Điểm tin nhanh Ngành Nông Nghiệp – AgriS"
description: "AgriS • Cập nhật định kỳ theo tháng/tuần"
url: ""        # để trống nếu deploy bằng GitHub Pages (nhánh main)
baseurl: ""    # để trống

markdown: kramdown
highlighter: rouge

# KHÔNG đặt theme: nil (giữ nguyên comment để tránh lỗi)
# theme:

# Hai collections: tháng & tuần
collections:
  months:
    output: true
    permalink: /:collection/:name/
  weeks:
    output: true
    permalink: /:collection/:name/

# Giá trị mặc định theo từng collection
defaults:
  - scope:
      path: "_months"
      type: "months"
    values:
      layout: month
      type: month
  - scope:
      path: "_weeks"
      type: "weeks"
    values:
      layout: week
      type: week

# Các thư mục cần build
include:
  - _includes
  - _layouts
  - assets
  - _months
  - _weeks

# Plugins chuẩn (không bắt buộc)
plugins: []
