# _config.yml — Jekyll + GitHub Pages

title: "News-letter"
description: "Điểm tin nhanh Ngành Nông Nghiệp – AgriS"
url: ""          # nếu deploy dạng nnt471-collab.github.io/<repo>, để trống
baseurl: ""      # để trống khi deploy trên nhánh main

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM            # hỗ trợ fenced code, table, v.v.
  hard_wrap: false
  syntax_highlighter_opts:
    span:
      line_numbers: false

# Collections
collections:
  months:
    output: true
    permalink: /:collection/:name/
  # mở nếu cần dùng tuần:
  # weeks:
  #   output: true
  #   permalink: /:collection/:name/

# Mặc định cho months
defaults:
  - scope:
      path: ""
      type: "months"
    values:
      layout: month
      type: month
  # mở nếu xài weeks:
  # - scope:
  #     path: ""
  #     type: "weeks"
  #   values:
  #     layout: week
  #     type: week

include:
  - _includes
  - _layouts
  - assets

plugins: []       # để trống cho GitHub Pages (không custom plugin)
